name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest
      - name: Run make
        run: cd app/consapp && make
      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
          name: RTKLib-all
          path: "../../"
